version: '3'
services:
  development:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
      
  test:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - '3001:3000'
    volumes:
      - /app/node_modules
      - .:/app
    
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
